[package]
name = "usbd-ctaphid"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/usbd-ctaphid"
repository = "https://github.com/trussed-dev/usbd-ctaphid"
description = "usb-device driver for CTAPHID"
categories = ["embedded", "no-std"]

[dependencies]
ctap-types = { path = "../ctap-types_fork" }
ctaphid-dispatch = "0.1.0"
embedded-time = "0.12"
delog = "0.1.0"
heapless = "0.7"
heapless-bytes = "0.3"
interchange = "0.3.0"
serde = { version = "1.0", default-features = false }
usb-device = "0.2.3"
ref-swap = "0.1.2"
trussed = { path = "../trussed_fork" }


[features]
default = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[patch.crates-io]
ctaphid-dispatch = { git = "https://github.com/trussed-dev/ctaphid-dispatch.git", rev = "57cb3317878a8593847595319aa03ef17c29ec5b" }
